### ISSUE TITLE
the link of course 15-418 points to 15-213

### ISSUE THREAD

**Issue by Sorosliu1029** [fanpu/fanpu.github.io#12]
https://github.com/fanpu/website/blob/2d4e127c392caa8f8735add784bf6bad493c2079/_data/cmu_online.yml#L424-L425

the current homepage of 15-418 is https://www.cs.cmu.edu/~418/, but I cannot find link to 2016 spring in resources section.

**Comment by fanpu** [comment]
Hey Soros, sorry I somehow missed this! This has been corrected in #fa6b15b0a9823088196d713a70cde0db42e310c6, I'll just point it to the current iteration of the course as the 2016 course website may have already been archived. Thank you!
